# Dictionary to map out names from steam stats names to more user-friendly names.

user_stats_names_map = {'acquired_lowgradefuel': 'gathered_lowgrade',
'acquired_metal.ore': 'gathered_metal_ore',
'acquired_scrap': 'gathered_scrap',
'arrow_fired': 'arrows_fired',
'arrow_hit_bear': 'arrows_hit_bears',
'arrow_hit_boar': 'arrows_hit_boars',
'arrow_hit_building': 'arrows_hit_buildings',
'arrow_hit_chicken': 'arrows_hit_chickens',
'arrow_hit_entity': 'arrows_hit_entities',
'arrow_hit_horse': 'arrows_hit_horses',
'arrow_hit_player': 'arrows_hit_players',
'arrow_hit_stag': 'arrows_hit_deer',
'arrow_hit_wolf': 'arrows_hit_wolfs',
'arrows_shot': 'arrows_shot',
'blueprint_studied': 'blueprints_learned',
'bullet_fired': 'bullets_fired',
'bullet_hit_bear': 'bullets_hit_bears',
'bullet_hit_boar': 'bullets_hit_boars',
'bullet_hit_building': 'bullets_hit_buildings',
'bullet_hit_corpse': 'bullets_hit_corpses',
'bullet_hit_entity': 'bullets_hit_entities',
'bullet_hit_horse': 'bullets_hit_horses',
'bullet_hit_player': 'bullets_hit_players',
'bullet_hit_playercorpse': 'bullets_hit_player_corpses',
'bullet_hit_sign': 'bullets_hit_signs',
'bullet_hit_stag': 'bullets_hit_deer',
'bullet_hit_wolf': 'bullets_hit_wolfs',
'calories_consumed': 'calories_consumed',
'cargoship_bridge_visits': 'cargoship_bridge_visits',
'cold_exposure_duration': 'cold_exposure_duration',
'comfort_duration': 'comfort_exposure_duration',
'crafting_opened': 'crafting_menu_opened',
'cupboard_opened': 'cupboards_opened',
'death_bear': 'deaths_to_bears',
'death_entity': 'deaths_to_entities',
'death_fall': 'deaths_to_fall',
'death_selfinflicted': 'deaths_to_selfinflicted',
'death_wolf': 'deaths_to_wolf',
'deaths': 'deaths',
'destroyed_barrels': 'destroyed_barrels',
'harvested_cloth': 'gathered_cloth',
'harvested_leather': 'gathered_leather',
'harvested_stones': 'gathered_stone',
'harvested_wood': 'gathered_wood',
'headshot': 'headshots',
'helipad_landings': 'oilrig_helipad_landings',
'horse_distance_ridden': 'horse_distance_ridden',
'horse_distance_ridden_km': 'horse_distance_ridden_km',
'hot_exposure_duration': 'overheated_exposure_duration',
'instrumentfullkeyboardmode': 'instruments_full_keyboard_mode',
'instrumentnotesplayed': 'instruments_notes_played',
'instrumentnotesplayedbinds': 'instruments_notes_played_binds',
'inventory_opened': 'inventory_opened',
'item_drop': 'items_dropped',
'item_examined': 'items_examined',
'kill_bear': 'kill_bears',
'kill_boar': 'kill_boars',
'kill_chicken': 'kill_chickens',
'kill_horse': 'kill_horses',
'kill_player': 'kill_players',
'kill_scientist': 'kill_scientists',
'kill_stag': 'kill_deer',
'kill_wolf': 'kill_wolfs',
'map_opened': 'map_opened',
'melee_strikes': 'melee_strikes',
'melee_thrown': 'melee_throws',
'pickup_category_food': 'picked_up_food_items',
'placed_blocks': 'placed_blocks',
'radiation_exposure_duration': 'radiation_exposure_duration',
'recycled_cans': 'recycled_cans',
'rocket_fired': 'rockets_fired',
'seconds_speaking': 'voice_chat_seconds',
'shotgun_fired': 'shotguns_fired',
'shotgun_hit_building': 'shotgun_bullets_hit_building',
'shotgun_hit_entity': 'shotgun_bullets_hit_entities',
'shotgun_hit_horse': 'shotgun_bullets_hit_horse',
'shotgun_hit_player': 'shotgun_bullets_hit_player',
'topology_road_duration': 'topology_road_duration',
'upgraded_blocks': 'blocks_upgraded',
'water_consumed': 'water_consumed',
'wounded': 'wounded',
'wounded_assisted': 'wounded_assisted',
'wounded_healed': 'wounded_healed',
'harvest.cloth': None,  # These should be removed when remove_player_stats_duplicates is called
'harvest.stones': None,
'harvest.wood': None,
'death_suicide': None,
}

top_categories = [
    ["hours_played", "Hours Played"],
    ["kill_players", "Player Kills"],
    ["kill_scientists", "Scientist Kills"],
    ["bullets_fired", "Bullets Fired"],
    ["bullets_hit_players", "Bullets hit Players"],
    ["shotgun_bullets_hit_player", "Shotguns hit Players"],
    ["headshots", "Headshots"],
    ["rockets_fired", "Rockets Fired"],
    ["arrows_hit_players", "Arrows hit Players"],
    ["deaths", "Deaths"],
    ["deaths_to_selfinflicted", "Selfinflicted Deaths"],
    ["wounded", "Wounded"],
    ["wounded_assisted", "Wounded Assisted"],
    ["wounded_healed", "Wounded Self-Healed"],
    ["voice_chat_seconds", "Voicechat Time"],
    ["blocks_upgraded", "Blocks Upgraded"],
    ["placed_blocks", "Blocks Placed"],
    ["melee_strikes", "Melee Strikes"],
    ["cold_exposure_duration", "Cold Exposure"],
    ["radiation_exposure_duration", "Radiation Exposure"],
    ["gathered_cloth", "Gathered Cloth"],
    ["gathered_metal_ore", "Gathered Metal Ore"],
    ["gathered_wood", "Gathered Wood"],
    ["gathered_stone", "Gathered Stone"],
    ["gathered_scrap", "Gathered Scrap"],
    ["horse_distance_ridden_km", "Horse Ridden in KM"],
    ["instruments_notes_played", "Notes Played"],
    ["items_dropped", "Items Dropped"],
    ["items_examined", "Items Inspected"],
    ["blueprints_learned", "Blueprints Learned"],
    ["calories_consumed", "Calories Consumed"],
    ["water_consumed", "Water Consumed"],
    ["oilrig_helipad_landings", "Oilrig Helipad Landings"],
    ["map_opened", "Map Opened"],
    ["inventory_opened", "Inventory Opened"],
    ["crafting_menu_opened", "Crafting Menu Opened"],

]