# Generated by Django 3.0.6 on 2020-06-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hours_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
