# Generated by Django 3.0.6 on 2020-06-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust_stats', '0004_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
