# Generated by Django 3.0.6 on 2020-06-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust_stats', '0005_user_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_user_friends_+', to='rust_stats.User'),
        ),
    ]
