# Generated by Django 3.0.6 on 2020-06-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rust_stats', '0006_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
